pipeline {
  agent any

  options {
    timestamps()
  }

  stages {
    stage('Helm - PostgreSQL Deploy') {
      steps {
        dir('helm/postgresql') {
          sh 'helm dependency update'
          sh 'helm upgrade --install my-postgres .'
        }
      }
    }

    stage('Helm - Redis Deploy') {
      steps {
        dir('helm/redis') {
          sh 'helm dependency update'
          sh 'helm upgrade --install my-redis .'
        }
      }
    }

    stage('Tests') {
      steps {
        sh 'bash scripts/test_postgres.sh'
        sh 'bash scripts/test_redis.sh'
      }
    }
  }

  post {
    success { echo '✅ Pipeline başarıyla tamamlandı!' }
    failure { echo '❌ Pipeline başarısız oldu.' }
  }
}
